spring:
  application:
    name: library-demo
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      format-sql: true

  server:
    port: 8082