version: '3.8'

services:
  lib_db:
    image: postgres:latest
    container_name: postgres_library_demo
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    volumes:
      - ./data_base:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always